# Generated by Django 5.0.6 on 2026-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=10),
        ),
    ]
